title: "Mavericks Edge Blog"
description: "Web design insights and strategies for Edmonton businesses"
url: "https://goodguyben.github.io"
baseurl: "/mavericksedge-beyondtheedge"

# Jekyll settings
markdown: kramdown
highlighter: rouge
permalink: /:year/:month/:day/:title/

# Default layout for posts
defaults:
  - scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "post"

# Build settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# SEO settings
author:
  name: "Bezal Benny"
  email: "bezal@mavericksedge.ca"
  bio: "Web design strategist helping Edmonton businesses grow online"
  location: "Edmonton, Alberta"
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://mavericksedge.ca"
